### PR TITLE
Fix `undo`/`redo` command and add proper success message

### LINKED ISSUE #85: Implement `undo` feature

### PR DESCRIPTION
**Pull request by NhatMinh0208**
Resolves #85. With this the undo/redo feature should be ready to go.

### CODE REVIEW

File: src/main/java/seedu/address/model/modifications/Modification.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
+package seedu.address.model.modifications;
+
+import seedu.address.commons.util.ToStringBuilder;
+import seedu.address.model.person.Person;
+
+/**
+ * Abstract class representing a record of a modification to the address book.
+ */
+public abstract class Modification {
```
Comment (Masunori) [inline src/main/java/seedu/address/model/modifications/Modification.java:9]: LGTM!

File: src/main/java/seedu/address/model/AddressBookStateNode.java [hunk 2]
```diff
@@ -44,7 +44,8 @@ public boolean equals(Object other) {
 
         AddressBookStateNode otherModelManager = (AddressBookStateNode) other;
         return state.equals(otherModelManager.state)
-                && ((command == null && otherModelManager.command == null)
-                || (command != null && otherModelManager.command != null && command.equals(otherModelManager.command)));
+                && ((modification == null && otherModelManager.modification == null)
+                || (modification != null && otherModelManager.modification != null
+                && modification.equals(otherModelManager.modification)));
```
Comment (Masunori) [inline src/main/java/seedu/address/model/AddressBookStateNode.java:49]: I think this part of logic can be splitted and rewritten for more readability:
```java
boolean areStatesEqual = state.equals(otherModelManager.state);

boolean areCommandsEqual = modification == null 
    ? otherModelManager.modification == null
    : modification.equals(otherModelManager.modification)));

return areStatesEqual && areCommandsEqual;
```

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 3]
```diff
@@ -68,7 +69,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.addPerson(toAdd);
-        model.commitAddressBook(this);
+        model.commitAddressBook(new AddMod(toAdd));
```
Comment (Masunori) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:72]: LGTM!

File: src/main/java/seedu/address/model/AddressBookStateNode.java (hunk 2 above)
Comment (NhatMinh0208) [reply src/main/java/seedu/address/model/AddressBookStateNode.java:49]: Good point.

**Comment by NhatMinh0208** [comment]
I'm just going to merge so you guys have time to test tomorrow
